// In-memory database
const employees = [
  {
    id: '1',
    name: 'John Smith',
    age: 28,
    class: 'Senior',
    subjects: ['JavaScript', 'React', 'Node.js'],
    attendance: 95.5,
    email: 'john.smith@company.com',
    phone: '+1-555-0101',
    department: 'Engineering',
    position: 'Senior Developer',
    joinDate: '2020-01-15',
    salary: 95000,
    address: '123 Tech Street, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    age: 32,
    class: 'Lead',
    subjects: ['Python', 'Django', 'PostgreSQL'],
    attendance: 98.2,
    email: 'sarah.johnson@company.com',
    phone: '+1-555-0102',
    department: 'Engineering',
    position: 'Tech Lead',
    joinDate: '2018-03-20',
    salary: 120000,
    address: '456 Innovation Ave, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '3',
    name: 'Michael Chen',
    age: 25,
    class: 'Junior',
    subjects: ['Java', 'Spring Boot', 'MySQL'],
    attendance: 92.8,
    email: 'michael.chen@company.com',
    phone: '+1-555-0103',
    department: 'Engineering',
    position: 'Junior Developer',
    joinDate: '2022-06-01',
    salary: 75000,
    address: '789 Code Lane, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '4',
    name: 'Emily Davis',
    age: 29,
    class: 'Senior',
    subjects: ['UI/UX', 'Figma', 'CSS'],
    attendance: 96.7,
    email: 'emily.davis@company.com',
    phone: '+1-555-0104',
    department: 'Design',
    position: 'Senior Designer',
    joinDate: '2019-09-10',
    salary: 90000,
    address: '321 Design Blvd, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '5',
    name: 'David Martinez',
    age: 35,
    class: 'Lead',
    subjects: ['AWS', 'DevOps', 'Kubernetes'],
    attendance: 94.3,
    email: 'david.martinez@company.com',
    phone: '+1-555-0105',
    department: 'Operations',
    position: 'DevOps Lead',
    joinDate: '2017-04-15',
    salary: 125000,
    address: '654 Cloud Drive, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '6',
    name: 'Lisa Anderson',
    age: 27,
    class: 'Mid-Level',
    subjects: ['Product Management', 'Agile', 'Jira'],
    attendance: 97.1,
    email: 'lisa.anderson@company.com',
    phone: '+1-555-0106',
    department: 'Product',
    position: 'Product Manager',
    joinDate: '2021-02-01',
    salary: 100000,
    address: '987 Product Way, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '7',
    name: 'James Wilson',
    age: 31,
    class: 'Senior',
    subjects: ['GraphQL', 'Apollo', 'TypeScript'],
    attendance: 93.5,
    email: 'james.wilson@company.com',
    phone: '+1-555-0107',
    department: 'Engineering',
    position: 'Senior Backend Developer',
    joinDate: '2019-07-20',
    salary: 105000,
    address: '159 API Street, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '8',
    name: 'Jennifer Lee',
    age: 26,
    class: 'Mid-Level',
    subjects: ['React Native', 'iOS', 'Android'],
    attendance: 91.8,
    email: 'jennifer.lee@company.com',
    phone: '+1-555-0108',
    department: 'Engineering',
    position: 'Mobile Developer',
    joinDate: '2021-11-15',
    salary: 85000,
    address: '753 Mobile Ave, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '9',
    name: 'Robert Taylor',
    age: 38,
    class: 'Manager',
    subjects: ['Leadership', 'Strategy', 'Team Management'],
    attendance: 99.0,
    email: 'robert.taylor@company.com',
    phone: '+1-555-0109',
    department: 'Management',
    position: 'Engineering Manager',
    joinDate: '2016-01-10',
    salary: 140000,
    address: '852 Manager Court, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '10',
    name: 'Maria Garcia',
    age: 24,
    class: 'Junior',
    subjects: ['HTML', 'CSS', 'JavaScript'],
    attendance: 90.2,
    email: 'maria.garcia@company.com',
    phone: '+1-555-0110',
    department: 'Engineering',
    position: 'Frontend Developer',
    joinDate: '2023-01-05',
    salary: 70000,
    address: '951 Frontend Plaza, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '11',
    name: 'Christopher Brown',
    age: 33,
    class: 'Senior',
    subjects: ['Data Science', 'Python', 'ML'],
    attendance: 95.8,
    email: 'christopher.brown@company.com',
    phone: '+1-555-0111',
    department: 'Data',
    position: 'Data Scientist',
    joinDate: '2018-08-20',
    salary: 115000,
    address: '357 Data Drive, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '12',
    name: 'Amanda White',
    age: 30,
    class: 'Senior',
    subjects: ['Security', 'Penetration Testing', 'OWASP'],
    attendance: 97.5,
    email: 'amanda.white@company.com',
    phone: '+1-555-0112',
    department: 'Security',
    position: 'Security Engineer',
    joinDate: '2019-05-12',
    salary: 110000,
    address: '159 Security Blvd, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '13',
    name: 'Amanda White',
    age: 30,
    class: 'Senior',
    subjects: ['Security', 'Penetration Testing', 'OWASP'],
    attendance: 97.5,
    email: 'amanda.white@company.com',
    phone: '+1-555-0112',
    department: 'Security',
    position: 'Security Engineer',
    joinDate: '2019-05-12',
    salary: 110000,
    address: '159 Security Blvd, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '14',
    name: 'Amanda White',
    age: 30,
    class: 'Senior',
    subjects: ['Security', 'Penetration Testing', 'OWASP'],
    attendance: 97.5,
    email: 'amanda.white@company.com',
    phone: '+1-555-0112',
    department: 'Security',
    position: 'Security Engineer',
    joinDate: '2019-05-12',
    salary: 110000,
    address: '159 Security Blvd, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '15',
    name: 'Amanda White',
    age: 30,
    class: 'Senior',
    subjects: ['Security', 'Penetration Testing', 'OWASP'],
    attendance: 97.5,
    email: 'amanda.white@company.com',
    phone: '+1-555-0112',
    department: 'Security',
    position: 'Security Engineer',
    joinDate: '2019-05-12',
    salary: 110000,
    address: '159 Security Blvd, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '16',
    name: 'Amanda White',
    age: 30,
    class: 'Senior',
    subjects: ['Security', 'Penetration Testing', 'OWASP'],
    attendance: 97.5,
    email: 'amanda.white@company.com',
    phone: '+1-555-0112',
    department: 'Security',
    position: 'Security Engineer',
    joinDate: '2019-05-12',
    salary: 110000,
    address: '159 Security Blvd, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '17',
    name: 'Amanda White',
    age: 30,
    class: 'Senior',
    subjects: ['Security', 'Penetration Testing', 'OWASP'],
    attendance: 97.5,
    email: 'amanda.white@company.com',
    phone: '+1-555-0112',
    department: 'Security',
    position: 'Security Engineer',
    joinDate: '2019-05-12',
    salary: 110000,
    address: '159 Security Blvd, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '18',
    name: 'Amanda White',
    age: 30,
    class: 'Senior',
    subjects: ['Security', 'Penetration Testing', 'OWASP'],
    attendance: 97.5,
    email: 'amanda.white@company.com',
    phone: '+1-555-0112',
    department: 'Security',
    position: 'Security Engineer',
    joinDate: '2019-05-12',
    salary: 110000,
    address: '159 Security Blvd, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '19',
    name: 'Amanda White',
    age: 30,
    class: 'Senior',
    subjects: ['Security', 'Penetration Testing', 'OWASP'],
    attendance: 97.5,
    email: 'amanda.white@company.com',
    phone: '+1-555-0112',
    department: 'Security',
    position: 'Security Engineer',
    joinDate: '2019-05-12',
    salary: 110000,
    address: '159 Security Blvd, San Francisco, CA',
    status: 'Active'
  },  
  {
    id: '12',
    name: 'Amanda White',
    age: 30,
    class: 'Senior',
    subjects: ['Security', 'Penetration Testing', 'OWASP'],
    attendance: 97.5,
    email: 'amanda.white@company.com',
    phone: '+1-555-0112',
    department: 'Security',
    position: 'Security Engineer',
    joinDate: '2019-05-12',
    salary: 110000,
    address: '159 Security Blvd, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '20',
    name: 'Amanda White',
    age: 30,
    class: 'Senior',
    subjects: ['Security', 'Penetration Testing', 'OWASP'],
    attendance: 97.5,
    email: 'amanda.white@company.com',
    phone: '+1-555-0112',
    department: 'Security',
    position: 'Security Engineer',
    joinDate: '2019-05-12',
    salary: 110000,
    address: '159 Security Blvd, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '21',
    name: 'Amanda White',
    age: 30,
    class: 'Senior',
    subjects: ['Security', 'Penetration Testing', 'OWASP'],
    attendance: 97.5,
    email: 'amanda.white@company.com',
    phone: '+1-555-0112',
    department: 'Security',
    position: 'Security Engineer',
    joinDate: '2019-05-12',
    salary: 110000,
    address: '159 Security Blvd, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '22',
    name: 'Amanda White',
    age: 30,
    class: 'Senior',
    subjects: ['Security', 'Penetration Testing', 'OWASP'],
    attendance: 97.5,
    email: 'amanda.white@company.com',
    phone: '+1-555-0112',
    department: 'Security',
    position: 'Security Engineer',
    joinDate: '2019-05-12',
    salary: 110000,
    address: '159 Security Blvd, San Francisco, CA',
    status: 'Active'
  },
  {
    id: '23',
    name: 'Amanda White',
    age: 30,
    class: 'Senior',
    subjects: ['Security', 'Penetration Testing', 'OWASP'],
    attendance: 97.5,
    email: 'amanda.white@company.com',
    phone: '+1-555-0112',
    department: 'Security',
    position: 'Security Engineer',
    joinDate: '2019-05-12',
    salary: 110000,
    address: '159 Security Blvd, San Francisco, CA',
    status: 'Active'
  }
];

const users = [
  {
    id: '1',
    username: 'admin',
    email: 'admin@company.com',
    password: '$2b$10$B3pv6sB6RCFRv6kcxCSGPeWvGfd7LZgo9d3dBLOSguaArWEET.FXG', // password: admin123
    role: 'admin'
  },
  {
    id: '2',
    username: 'employee',
    email: 'employee@company.com',
    password: '$2b$10$P.7u/KJ.HIM7PtFKddGReOgQT.3/dwySwcnqdxSfKU4iPuAxvu2lW', // password: employee123
    role: 'employee'
  }
];

module.exports = { employees, users };

